-- Cynovela Phase 3: 関係層 Postgres consolidated DDL（自動生成）
-- 生成元: tools/pg_consolidated_ddl.py（SQLite demo.db → sqlglot 変換 + 方言吸収）
-- 日時列 TEXT 維持 / IDENTITY 化 / sensitivity_score DOUBLE PRECISION / pgvector 同居。
CREATE EXTENSION IF NOT EXISTS vector;

-- table: acl_users
CREATE TABLE IF NOT EXISTS acl_users (id TEXT PRIMARY KEY, display_name TEXT NOT NULL DEFAULT '', role TEXT NOT NULL, department TEXT DEFAULT '', avatar TEXT DEFAULT '', created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')));

-- table: admin_change_log
CREATE TABLE IF NOT EXISTS admin_change_log (id TEXT PRIMARY KEY, timestamp TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), changed_by TEXT NOT NULL DEFAULT 'unknown', entity_type TEXT NOT NULL, entity_id TEXT, action TEXT NOT NULL, before_value TEXT, after_value TEXT);

-- table: audit_logs
CREATE TABLE IF NOT EXISTS audit_logs (id TEXT PRIMARY KEY, timestamp TEXT DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), user_id TEXT, action TEXT NOT NULL, target TEXT, detail TEXT, ip_address TEXT DEFAULT NULL, result TEXT DEFAULT NULL, category TEXT DEFAULT NULL);

-- table: blocked_topics
CREATE TABLE IF NOT EXISTS blocked_topics (id TEXT PRIMARY KEY, name TEXT NOT NULL, pattern TEXT NOT NULL, is_regex INT NOT NULL DEFAULT 0, action TEXT NOT NULL DEFAULT 'block', created_by TEXT NOT NULL DEFAULT 'unknown', created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), is_active INT NOT NULL DEFAULT 1);

-- table: collection_locks
CREATE TABLE IF NOT EXISTS collection_locks (collection_id TEXT PRIMARY KEY, locked_by TEXT, locked_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')));

-- table: feedback
CREATE TABLE IF NOT EXISTS feedback (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, message_id TEXT, rating INT NOT NULL, comment TEXT, created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), query_id TEXT, query TEXT, answer_preview TEXT, sources_used TEXT, mode TEXT, collection_id TEXT, workspace_id TEXT, response_time_ms INT, crag_triggered INT DEFAULT 0, multi_query_count INT DEFAULT 1);

-- table: file_hashes
CREATE TABLE IF NOT EXISTS file_hashes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, collection_id TEXT NOT NULL, file_path TEXT NOT NULL, sha256 TEXT NOT NULL, chunk_ids TEXT NOT NULL DEFAULT '[]', scanned_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), pdf_mode TEXT NOT NULL DEFAULT 'fast', UNIQUE (collection_id, file_path));

-- table: guardrail_policies
CREATE TABLE IF NOT EXISTS guardrail_policies (id TEXT PRIMARY KEY, name TEXT NOT NULL, rules TEXT NOT NULL DEFAULT '[]', state TEXT DEFAULT 'active' CHECK (state IN ('active', 'inactive')), created_at TEXT DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')));

-- table: message_rag_refs
CREATE TABLE IF NOT EXISTS message_rag_refs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, message_id TEXT NOT NULL, logical_chunk_id TEXT NOT NULL, vector_id TEXT NOT NULL, rank INT NOT NULL, score REAL, source_path TEXT, created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')));

-- table: messages
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, session_id TEXT NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, content_hash TEXT NOT NULL, model_name TEXT, redaction_status TEXT NOT NULL DEFAULT 'clean', pii_flags_json TEXT NOT NULL DEFAULT '[]', token_count INT, latency_ms INT, created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), retrieval_json TEXT);

-- table: pipeline_presets
CREATE TABLE IF NOT EXISTS pipeline_presets (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT, config_json TEXT NOT NULL, is_builtin INT DEFAULT 0, created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')));

-- table: processing_logs
CREATE TABLE IF NOT EXISTS processing_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, timestamp TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), log_type TEXT NOT NULL /* 'publish' or 'rag_query' */, job_id TEXT /* Publish job ID or query ID (任意) */, level TEXT NOT NULL DEFAULT 'info' /* info / warning / error / success */, message TEXT NOT NULL, metadata_json TEXT /* 任意: チャンク数 / 処理時間等 */);

-- table: publish_history
CREATE TABLE IF NOT EXISTS publish_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, workspace_id TEXT NOT NULL, timestamp TEXT NOT NULL, doc_count INT DEFAULT 0, chunk_count INT DEFAULT 0, pii_count INT DEFAULT 0, excluded_count INT DEFAULT 0, avg_chunk_chars REAL DEFAULT 0, elapsed_seconds REAL DEFAULT 0);

-- table: publish_jobs
CREATE TABLE IF NOT EXISTS publish_jobs (id TEXT PRIMARY KEY, collection_id TEXT NOT NULL, status TEXT DEFAULT 'pending', stage TEXT DEFAULT '', progress INT DEFAULT 0, total INT DEFAULT 0, message TEXT DEFAULT '', error TEXT DEFAULT NULL, created_at TEXT DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), updated_at TEXT DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), cancel_requested INT DEFAULT 0);

-- table: reports
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, report_type TEXT NOT NULL, content TEXT NOT NULL, generated_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), generated_by TEXT NOT NULL DEFAULT 'unknown', days_covered INT NOT NULL DEFAULT 30);

-- table: schema_migrations
CREATE TABLE IF NOT EXISTS schema_migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL, description TEXT);

-- table: sessions
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, workspace_id TEXT NOT NULL, system_prompt_id TEXT, title TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), updated_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), token_usage TEXT);

-- table: settings
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT);

-- table: sources
CREATE TABLE IF NOT EXISTS sources (id TEXT PRIMARY KEY, name TEXT NOT NULL, path TEXT NOT NULL, status TEXT DEFAULT 'idle' CHECK (status IN ('idle', 'scanning', 'completed', 'failed', 'canceled')), file_count INT DEFAULT 0, last_scanned TEXT, created_at TEXT DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), archived_at TEXT DEFAULT NULL, archived_by TEXT, cancel_requested INT DEFAULT 0);

-- DD-CYN-0143 C-6/C-11: 走査の中止を状態で判別できる形 (migration 0009 の Postgres 側)。
-- 既存 DB へも冪等に追随させる: cancel_requested 列と、status CHECK への 'canceled' 追加。
ALTER TABLE sources ADD COLUMN IF NOT EXISTS cancel_requested INT DEFAULT 0;
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.check_constraints cc
    JOIN information_schema.constraint_column_usage u USING (constraint_schema, constraint_name)
    WHERE u.table_name = 'sources' AND cc.check_clause NOT LIKE '%canceled%' AND cc.check_clause LIKE '%scanning%'
  ) THEN
    EXECUTE (
      SELECT 'ALTER TABLE sources DROP CONSTRAINT ' || quote_ident(cc.constraint_name)
      FROM information_schema.check_constraints cc
      JOIN information_schema.constraint_column_usage u USING (constraint_schema, constraint_name)
      WHERE u.table_name = 'sources' AND cc.check_clause NOT LIKE '%canceled%' AND cc.check_clause LIKE '%scanning%'
      LIMIT 1
    );
    ALTER TABLE sources ADD CONSTRAINT sources_status_check
      CHECK (status IN ('idle', 'scanning', 'completed', 'failed', 'canceled'));
  END IF;
END $$;

-- table: system_prompts
CREATE TABLE IF NOT EXISTS system_prompts (id TEXT PRIMARY KEY, prompt_name TEXT NOT NULL, prompt_version TEXT NOT NULL DEFAULT 'v1', prompt_text TEXT NOT NULL, prompt_hash TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')));

-- table: users
CREATE TABLE IF NOT EXISTS "users" (id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL CHECK (role IN ('admin', 'viewer')), avatar TEXT, username TEXT, display_name TEXT, password_hash TEXT, is_active INT DEFAULT 1, created_at TEXT, updated_at TEXT, must_change_password INT, password_changed_at BIGINT);
-- agentK K-1 (q5 B1): パスワード変更時刻 (UTC epoch 秒)。これより前に発行された JWT (iat) を
-- core/auth.py が拒否する。SQLite 側は db.py migrate_db の ALTER と対。既存 DB にも冪等追加。
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS password_changed_at BIGINT;

-- table: workspaces
CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, guardrail_policy_id TEXT REFERENCES guardrail_policies (id), created_at TEXT DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), sync_config TEXT DEFAULT NULL, description TEXT DEFAULT '', updated_at TEXT, acl_config TEXT DEFAULT NULL, archived_at TEXT DEFAULT NULL, archived_by TEXT);

-- table: collections
CREATE TABLE IF NOT EXISTS "collections" (id TEXT PRIMARY KEY, name TEXT NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE, status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'ingested', 'publishing', 'ready', 'failed', 'stopped', 'interrupted')), access_level TEXT DEFAULT 'public' CHECK (access_level IN ('public', 'internal', 'confidential')), chunk_count INT DEFAULT 0, created_at TEXT DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), allowed_roles_json TEXT, rag_strategy TEXT DEFAULT 'hybrid_bm25', chunk_size INT, chunk_overlap INT, rag_mode TEXT, acl_roles TEXT DEFAULT NULL, last_published_at TEXT DEFAULT NULL, archived_at TEXT DEFAULT NULL, archived_by TEXT, raw_only INT DEFAULT 0);
-- DD-CYN-0115 (H-7): raw_only は 2026-07-19 に実クラスタへ手当てされたが DDL 未反映だった列。
-- 既存 DB へも冪等に追随させる (機能は廃止済み・列は互換のため保全)。
ALTER TABLE "collections" ADD COLUMN IF NOT EXISTS raw_only INT DEFAULT 0;

-- table: document_lineage
CREATE TABLE IF NOT EXISTS "document_lineage" (id TEXT PRIMARY KEY, file_id TEXT NOT NULL, workspace_id TEXT NOT NULL, collection_id TEXT REFERENCES collections (id) ON DELETE CASCADE, source_path TEXT NOT NULL, file_hash TEXT NOT NULL, file_size INT, chunk_count INT DEFAULT 0, publish_version INT DEFAULT 1, acl_source TEXT DEFAULT 'cynovela', created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), updated_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')));

-- table: document_provenance
CREATE TABLE IF NOT EXISTS "document_provenance" (id TEXT PRIMARY KEY, document_id TEXT NOT NULL, collection_id TEXT NOT NULL REFERENCES collections (id) ON DELETE CASCADE, filename TEXT NOT NULL, sha256 TEXT NOT NULL, file_size INT, version INT NOT NULL DEFAULT 1, published_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), published_by TEXT NOT NULL DEFAULT 'unknown', is_current INT NOT NULL DEFAULT 1, embedding_version TEXT, embedding_model TEXT);

-- table: files
CREATE TABLE IF NOT EXISTS files (id TEXT PRIMARY KEY, source_id TEXT NOT NULL REFERENCES sources (id) ON DELETE CASCADE, name TEXT NOT NULL, path TEXT NOT NULL, size INT, mime_type TEXT, categories TEXT DEFAULT '[]', scanned_at TEXT DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), owner TEXT, department TEXT, project TEXT, doc_type TEXT, sensitivity_level TEXT, sensitivity_score DOUBLE PRECISION, metadata_enriched_at TEXT, refreshed_at TEXT, classification TEXT DEFAULT NULL, classified_at TEXT DEFAULT NULL, sensitivity TEXT DEFAULT 'public', auto_tags TEXT DEFAULT '[]', freshness_days INT DEFAULT NULL, expires_at TEXT DEFAULT NULL, missing INT NOT NULL DEFAULT 0);
-- schema-parity fix (pre-ga-fix-all-20260720): 既存DBにも missing 列を冪等追加する。
-- server.py _do_scan / _detect_workspace_changes が files.missing を読み書きするが SQLite の
-- migrate_db(db.py) 相当が PG 側に無いため、姉妹系統 SQLite の定義 (INTEGER NOT NULL DEFAULT 0) に合わせて補う。
ALTER TABLE files ADD COLUMN IF NOT EXISTS missing INT NOT NULL DEFAULT 0;

-- table: parent_chunks
CREATE TABLE IF NOT EXISTS "parent_chunks" (parent_id TEXT PRIMARY KEY, collection_id TEXT NOT NULL REFERENCES collections (id) ON DELETE CASCADE, workspace_id TEXT NOT NULL, source_doc TEXT DEFAULT '', content TEXT NOT NULL, char_count INT DEFAULT 0, created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), tier TEXT DEFAULT 'raw', pii_summary TEXT DEFAULT NULL);

-- table: refresh_tokens
CREATE TABLE IF NOT EXISTS refresh_tokens (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')));

-- table: workspace_policies
CREATE TABLE IF NOT EXISTS workspace_policies (workspace_id TEXT NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE, policy_id TEXT NOT NULL REFERENCES guardrail_policies (id) ON DELETE CASCADE, PRIMARY KEY (workspace_id, policy_id));

-- table: workspace_sources
CREATE TABLE IF NOT EXISTS workspace_sources (workspace_id TEXT NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE, source_id TEXT NOT NULL REFERENCES sources (id) ON DELETE CASCADE, PRIMARY KEY (workspace_id, source_id));

-- table: workspace_users
CREATE TABLE IF NOT EXISTS workspace_users (workspace_id TEXT NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE, PRIMARY KEY (workspace_id, user_id));

-- table: chunks
CREATE TABLE IF NOT EXISTS "chunks" (chunk_id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL, collection_id TEXT NOT NULL REFERENCES collections (id) ON DELETE CASCADE, source_doc TEXT DEFAULT '', page_hint INT, char_count INT DEFAULT 0, pii_detected INT DEFAULT 0, excluded INT DEFAULT 0, content TEXT DEFAULT '', acl_roles TEXT, context_text TEXT, last_accessed_at TEXT, tier TEXT DEFAULT 'raw', pii_summary TEXT DEFAULT NULL);

-- table: collection_files
CREATE TABLE IF NOT EXISTS collection_files (collection_id TEXT NOT NULL REFERENCES collections (id) ON DELETE CASCADE, file_id TEXT NOT NULL REFERENCES files (id) ON DELETE CASCADE, PRIMARY KEY (collection_id, file_id));

-- indexes
CREATE INDEX IF NOT EXISTS idx_admin_log_ts ON admin_change_log(timestamp DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_chunks_collection_tier ON chunks(collection_id NULLS FIRST, tier NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_feedback_created ON feedback(created_at NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_feedback_message ON feedback(message_id NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_feedback_rating ON feedback(rating NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_lineage_file_id ON document_lineage(file_id NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_lineage_hash ON document_lineage(file_hash NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_lineage_path ON document_lineage(workspace_id NULLS FIRST, source_path NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_lineage_workspace ON document_lineage(workspace_id NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id NULLS FIRST, created_at NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_parent_collection ON parent_chunks(collection_id NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_parent_collection_tier ON parent_chunks(collection_id NULLS FIRST, tier NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_proc_logs_job ON processing_logs(job_id NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_proc_logs_type_ts ON processing_logs(log_type NULLS FIRST, timestamp NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_provenance_collection ON document_provenance(collection_id NULLS FIRST, document_id NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_rag_refs_message ON message_rag_refs(message_id NULLS FIRST, rank NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_reports_ts ON reports(generated_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_rt_expires ON refresh_tokens(expires_at NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_rt_user ON refresh_tokens(user_id NULLS FIRST);
CREATE INDEX IF NOT EXISTS idx_sessions_ws_user ON sessions(workspace_id NULLS FIRST, user_id NULLS FIRST);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sources_name ON sources(name NULLS FIRST);

-- DD-CYN-0136 2-1: 用途を限定した鍵 (api_keys)。DD-CYN-0132 4-2 は SQLite 側 migrate_db にのみ
-- 追加しており、Postgres の空DB初期化経路 (本ファイル) に欠けていた。db.py の定義を Postgres 方言へ写す。
CREATE TABLE IF NOT EXISTS api_keys (id TEXT PRIMARY KEY, name TEXT NOT NULL DEFAULT '', key_prefix TEXT NOT NULL DEFAULT '', key_hash TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'viewer', scope_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT (TO_CHAR((CURRENT_TIMESTAMP AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')), created_by TEXT NOT NULL DEFAULT 'unknown', last_used_at TEXT, revoked_at TEXT);
CREATE INDEX IF NOT EXISTS idx_api_keys_hash ON api_keys(key_hash NULLS FIRST);

-- DD-CYN-0136 2-1: collections.egress_allowed (DD-CYN-0132 4-4)。既定 0 = 外へ出さない (fail-safe)。
ALTER TABLE collections ADD COLUMN IF NOT EXISTS egress_allowed INT NOT NULL DEFAULT 0;
